### ISSUE TITLE
nsfw filtered texts only file missing at step 08_01

### ISSUE THREAD

**Issue by shaharukhkhan4350** [huggingface/OBELICS#10]
Hi @HugoLaurencon ! 

Thanks for providing the code! Really helpful!

I am trying to reproduce the pipeline, however I am having issues to find this file at [line](https://github.com/huggingface/OBELICS/blob/main/build_obelics/08_01_prepare_urldedup.py#L18C1-L18C113):

```
PATH_WEB_DOCS_S3 = "s3://m4-datasets/webdocs/web_document_dataset_filtered_imgurldedup_nsfwfiltered_texts_only/"
```

As far as I can see, the output of file 7_03 is [this](https://github.com/huggingface/OBELICS/blob/main/build_obelics/07_03_nsfw_image_removal.py#L32). 

I am not sure how to get the `web_document_dataset_filtered_imgurldedup_nsfwfiltered_texts_only` dataset. Did I miss anything? 

Thanks for your response in advance! 

@shubhamagarwal92

**Comment by HugoLaurencon** [comment]
Hi thanks!

I think the output of 07_03 is rather
```
PATH_SAVE_S3_WEB_DOCS_NSFW_FILTERED = os.path.join(
    "s3://m4-datasets/webdocs/web_document_dataset_filtered_imgurldedup_nsfwfiltered", str(IDX_JOB)
)
```

In this case you can just replace the images by None to obtain your file

**Comment by shaharukhkhan4350** [comment]
Thanks @HugoLaurencon !

Closing the issue
