### ISSUE TITLE
Which folder to use? 

### ISSUE THREAD

**Issue by mckinziebrandon** [huggingface/OBELICS#2]
Hi, excellent work!

I've read the README a few times but I'm still not sure which directory (`obelics` or `build_obelics`) should be used to create the dataset. They both seem to do similar things in similar ways.

Also, it would be ideal if there was a set of instructions, rather than a directory of scripts each with different arguments, for obtaining the dataset.

**Comment by HugoLaurencon** [comment]
Hi @mckinziebrandon, thanks for your interest.

You should use `build_obelics` to obtain the scripts used for the creation of the dataset. These scripts call the methods defined in the folder `obelics`.

**Comment by mckinziebrandon** [comment]
Great, thanks!
